# Generated by Django 3.0.8 on 2020-07-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github', models.CharField(max_length=5000)),
                ('external_link', models.CharField(max_length=5000)),
                ('title', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=10000)),
                ('backend_tech', models.TextField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='------', max_length=6)),
                ('description_header', models.TextField(max_length=1000)),
                ('description_body', models.TextField(max_length=50000)),
                ('image', models.FileField(upload_to='image')),
                ('github', models.CharField(max_length=5000)),
                ('link', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.FileField(upload_to='stack_image')),
                ('tech', models.CharField(max_length=5000)),
                ('about_tech', models.TextField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stack',
                'ordering': ['-timestamp'],
            },
        ),
    ]
