# Generated by Django 3.0.8 on 2020-07-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='position',
            field=models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3')], default='------', max_length=6),
        ),
        migrations.AddField(
            model_name='stack',
            name='position',
            field=models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3')], default='------', max_length=6),
        ),
    ]
