# Generated by Django 3.0.8 on 2020-07-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200712_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='position',
            field=models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('others', 'Others')], default='------', max_length=6),
        ),
        migrations.AlterField(
            model_name='stack',
            name='position',
            field=models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('others', 'Others')], default='------', max_length=6),
        ),
    ]
