# Generated by Django 3.0.8 on 2020-07-13 04:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200713_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='stack',
            name='link',
            field=models.CharField(default=django.utils.timezone.now, max_length=2000),
            preserve_default=False,
        ),
    ]
