# Generated by Django 3.0.8 on 2020-07-18 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200718_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archive',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='archive',
            name='slug',
        ),
    ]
