# Generated by Django 3.0.8 on 2020-07-15 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='G_Stack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('others', 'Others')], default='------', max_length=6)),
                ('icon', models.FileField(upload_to='stack_image')),
                ('tech', models.CharField(max_length=5000)),
                ('about_tech', models.TextField(max_length=5000)),
                ('link', models.CharField(max_length=2000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stack',
                'verbose_name_plural': 'Stack',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Graphics_Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('others', 'Others')], default='------', max_length=6)),
                ('title', models.CharField(max_length=5000)),
                ('description', models.CharField(max_length=10000)),
                ('backend_tech', models.TextField(max_length=5000)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Graphics_Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('------', '------'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='------', max_length=6)),
                ('description_header', models.TextField(max_length=1000)),
                ('description_body', models.TextField(max_length=50000)),
                ('image', models.FileField(upload_to='image')),
                ('link', models.CharField(max_length=5000)),
            ],
            options={
                'verbose_name': 'Graphics Portfolio',
                'verbose_name_plural': 'Graphics Portfolio',
            },
        ),
        migrations.CreateModel(
            name='Mocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mocks', models.ImageField(upload_to='mocks', verbose_name='Mocks Images')),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphics.Graphics_Portfolio')),
            ],
            options={
                'verbose_name': 'Mocks (IMG)',
                'verbose_name_plural': 'Mocks (IMG)',
            },
        ),
        migrations.CreateModel(
            name='FinalDesigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_design', models.ImageField(upload_to='finaldesign', verbose_name='Final Design Images')),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphics.Graphics_Portfolio')),
            ],
            options={
                'verbose_name': 'Final Design (IMG)',
                'verbose_name_plural': 'Final Design (IMG)',
            },
        ),
        migrations.CreateModel(
            name='ArchiveFinalDesigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_design', models.ImageField(upload_to='achieve/finaldesign', verbose_name='Archieve Final Design Images')),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphics.Graphics_Archive')),
            ],
            options={
                'verbose_name': 'Archieve Final Design (IMG)',
                'verbose_name_plural': 'Archieve Final Design (IMG)',
            },
        ),
        migrations.CreateModel(
            name='AchieveMocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mocks', models.ImageField(upload_to='achieve/mocks', verbose_name='Archieve Mocks Images')),
                ('portfolio', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='graphics.Graphics_Archive')),
            ],
            options={
                'verbose_name': 'Archieve Mocks (IMG)',
                'verbose_name_plural': 'Archieve Mocks (IMG)',
            },
        ),
    ]
