# Generated by Django 3.0.8 on 2020-07-15 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='G_Stack',
            new_name='Graphics_Stack',
        ),
    ]
