# Generated by Django 3.0.8 on 2020-07-15 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0002_auto_20200715_1420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graphics_portfolio',
            name='link',
        ),
    ]
