# Generated by Django 3.0.8 on 2020-07-17 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0003_remove_graphics_portfolio_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tag',
            },
        ),
        migrations.AddField(
            model_name='graphics_archive',
            name='tag',
            field=models.ManyToManyField(to='graphics.Tag'),
        ),
        migrations.AddField(
            model_name='graphics_portfolio',
            name='tag',
            field=models.ManyToManyField(to='graphics.Tag'),
        ),
    ]
