# Generated by Django 3.0.8 on 2020-07-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphics', '0004_auto_20200717_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='graphics_archive',
            name='slug',
            field=models.SlugField(blank=True, help_text=' \n          When django prepopulate slugs, it normally omits prepositions, do not forget\n          to add it manually\n        ', null=True, unique=True),
        ),
    ]
